categories:
  - title: '🚀 Added'
    label: 'added'
  - title: '🔧 Fixed'
    label: 'fixed'
  - title: '⬆️ Dependencies'
    label: 'dependencies'
  - title: '🧹 Chore'
    label: 'chore'
exclude-labels:
  - 'skip-changelog'
template: |
  $CHANGES
